function English() {
	document.getElementById("silencio-desc").innerHTML="<i>Video performance in collaboration with the ensemble GILU</i>";
	document.getElementById("silencio-text").innerHTML="Silêncio de Chão conducts an improvised musical interpretation of poetic verses by Manoel de Barros, handpicked for their implicit musicality, interweaving meanings between words, images and sounds in a collectively constructed video performance, premiered at the <i>III International Colloquium \"Escrita, Som, Imagem\"</i>.<br><br>The audio was recorded remotely, in real time, with the aid of a computer program that draws, for each player, different verses of the work of Manoel de Barros, among which some were selected and visually interpreted in the footage that composes the work.<br><br>The program can be found by <a href=\"http://www.ofefo.com.br/mus/silencio\" target=\"_blank\">clicking here</a>.";
	document.getElementById("brutal-desc").innerHTML="<i>Interactive sculpture</i><br><br>Cement, biodegradable straws, rubber, epoxy, potentiometers, ultrasonic sensor, Arduino Nano and SuperCollider";
	document.getElementById("brutal-text").innerHTML="Inspired by the brutalist architectural movement, the sculpture seeks beauty in the simplicity of its materials, design and construction, serving as a control object for an equally uncomplicated and versatile FM synthesizer. The work emphasizes an intuitive and functional interaction between movements and sounds, which range from sinusoids to complex spectra.<br><br>Performed as a resident at <i>SomaRumor II - 2nd Latin American Meeting of Sound Art</i>. To access photos and a presentation video, <a href=\"http:\/\/www.ofefo.com.br/mus/brutal\" target=\"_blank\">click here</a>.";
	document.getElementById("engenhoca-text").innerHTML="<i>Improvising machine</i><br><br><img src=\"./mus/engenhoca/01.JPG\" style=\"max-width: 75%; text-justify: inter-word;\"><br><br><i>engenhoca</i> is a prototype implementation of a creative machine capable of improvising duos with musicians in real time. The project is intended as an inspiration for research in the area, enabling the expansion of educational and creative horizons of this musical activity.<br><br>Created as a Undergraduate Thesis in Music Education at UFMG, the project was entirely developed in the visual programming language Pure Data, freely distributed under the BSD license, while the machine is available under the GNU GPL 3.0 license, and its code hosted on GitHub.<br><br>To download the patch and listen to recordings with the system, <a href=\"http://www.ofefo.com.br/mus/engenhoca\" target=\"_blank\">click here</a>.";
	document.getElementById("welcomeBach-text").innerHTML="<i>Your daily dose of counterpoint</i><br><br>Python script to generate daily random picks of pieces not yet heard from a catalogue of a composer.<br>Initially designed to listen the entire BWV consistently, the project has grown an supports other composers, being possible to import more from <i>wikipedia</i> or <i>IMSLP</i> pages.<br><br>Being a free software, <i>welcomeBach</i> can be downloaded, modified or shared based on the users' interests (under the terms of the GNU GPLv2), and its code is hosted on <a href=\"https://github.com/ofefo/welcomeBach\" target=\"_blank\">GitHub</a>. <br><br>Contributions are welcome!";
	document.getElementById("emersao-text").innerHTML="<i>Soundscape composition</i><br><br>As they get closer to the surface, divers hear sounds transmuting...<br><br>December 2019";
	document.getElementById("ping-desc").innerHTML="<i>Interactive audiovisual system controled by musical improvisation</i><br>Developed with Caio Campos";
	document.getElementById("ping-text").innerHTML="PING is inpired by PONG, the classic ATARI game, reworked as an audiovisual system that interacts with musical improvisation, so that each side of this ping-pong is controlled by a musician who, instead of playing with a joystick (or racket), uses his instrument.<br><br> As in the original game, PING is a competition between two sides, but here, these sides can invert, multiply, expand and contract, or even bounce around the screen... and all this movement is controlled by the players with melodies, intensities and rhythms.<br><br>The dispute for points provides a stimulus for experimentation and musical expressiveness, while different levels and sound responses behave in unexpected ways, disturbing the internal logic of the game and weaving more layers in the interaction between musicians and the system.";
	document.getElementById("agora-desc").innerHTML="<i>Game for improvisation ensemble</i>";
	document.getElementById("agora-text").innerHTML="<br>Inspired by the Greek institution that is symbol for Athenian democracy, <i>agora</i> invites musicians to a musical assembly in which there is freedom to discuss any subject, provided that all participants have space for their voice to be heard.<br><br> The piece was written in October 2019 and premiered by the ensemble <i>Sonante 21</i> in the same month, in a concert conducted by Stephan Froleyks, in a project that involved scores written in just one day and with maximum of one page.<br>";
	document.getElementById("agora-rec").innerHTML="<br>The following recording is a realization of the piece by the ensemble <i>GILU</i>, in a concert at the first <i>FIM: Festival Improvisada Música</i>, in November 2019.<br><a href=\"./mus/agora.png\" target=\"_blank\">Score (in portuguese)</a>";
	document.getElementById("decampo-text").innerHTML="<i>Selected field recordings</i><br><br>Listening the space between a <i>chirp</i> here and a <i>vroom</i> there.<br><br>Recorded in Vitória/ES and Belo Horizonte/MG.<br>January - March 2019";
	document.getElementById("carnaval-text").innerHTML="<i>Festive noise</i><br><br>Teaser for <a href=\"https://www.youtube.com/watch?v=jEP_jgpSgaY\" target=\"_blank\">Blitzkrieg Noise #08</a><br><br>March 2019";
	document.getElementById("bifurcacoes-text").innerHTML="<i>Flute and live-electronics</i><br><br>You hear a high-pitched and syllabic music in the back and forth of the wind, foggy with leaves and distance. In this imaginary garden, time will perpetually fork into innumerable futures, revealing mirrored paths. Even though everything is decided at the moment, it will always be possible to listen to the past.<br><br>Inspired by the short story <i>The garden of forking paths</i> by Jorge Luis Borges.<br><br>Premiered by Rodrigo Frade at EBA-UFMG's Art Gallery.<br>December 2018";
	document.getElementById("bifurcacoes-rec").innerHTML="Reduced stereo version:";
	document.getElementById("praca6-text").innerHTML="<i>Noise music at a public square</i><br><br>Solo and duo of improvised noise music with Quasicrystal at Praça Sete (Belo Horizonte/MG), as part of the series \"<a href=\"https://www.youtube.com/watch?v=N65vxKMwXaI&list=PLhl6QLuwAA5HuX4UJheqv5SDjsWdt0jX9\" target=\"_blank\">Praça 6</a>\".<br><br>Played with SBOX (a joystick mapped as a digital instrument), a contact microphone and guitar pedals.<br><br>Recording and cover photo by Henrique Iwao.<br>Quasicrystal is Sannanda Acácia.<br>June 2018";
	document.getElementById("dysgraphia-text").innerHTML="<i>Defective acousmatic</i><br><br>Acoustic and synthesized sounds associate handwriting, typing, object manipulation and failures in electronic devices, seeking poetic coherence amid imperfection.<br><br>March 2018";
	document.getElementById("maestrandom-desc").innerHTML="<i>Musical instructions dice</i>";
	document.getElementById("maestrandom-text").innerHTML="Developed for a performance with the ensemble <i>GILU</i>. Keywords are chosen in random time intervals, coordenating the improvisation with some level of unpredictability. At the same time, instrumental groups are chosen at each minute to execute those ideas. The keywords were suggested by the ensemble members.";
	document.getElementById("maestrandom-patch").innerHTML="<a href=\"./maestro.pd\" download=\"maestro.pd\">Patch download (.pd)</a>";
	document.getElementById("cadaeco-text").innerHTML="<i>Soundscapes of chaos and cosiness<br>at an urban cave</i><br><br>Superposition of everyday sounds and instrumental improvisations. Featuring Luís Israel in \"chamada perdida\".<br><br>Recorded with a smartphone.<br>Cover photo by Arthur Moreira.<br>July - December 2015";
	document.getElementById("quatrocordas-text").innerHTML="<i>Four short improvisations with a guitar lacking two strings</i><br><br>Recorded with the computer microphone.<br>Cover in watercolor on paper<br>and digital editing.<br>May 2015";
}
